package com.tutorialsninja.dataproviders;

import com.tutorialsninja.util.TestDataGenerator;
import org.testng.annotations.DataProvider;

public class RegisterDataProvider {

    // This data provider generates test cases for valid registration data. It creates multiple instances of RegisterRequest using the ApisRequestHelper.
    // The number of test cases generated can be adjusted by changing the value of the numberOfTests variable. Each test case will contain a valid RegisterRequest object.
    // The parallel = true attribute allows TestNG to run the tests generated by this data provider in parallel, which can help speed up the execution of tests when there are many test cases.
    @DataProvider(name = "validRegistrationData", parallel = true)
    public Object[][] validRegistrationDataProvider() {
        // Provide multiple sets of RegisterRequest data for testing
        int numberOfTests = 3; // You can adjust this number to generate more or fewer test cases
        Object[][] data = new Object[numberOfTests][1];

        for (int i = 0; i < numberOfTests; i++) {
            data[i][0] = TestDataGenerator.getValidRegisterData();
        }
        return data;
    }



}
